language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
jdk:
  - oraclejdk8
script: ./scripts/travis-build.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)